# BUILD ENVIRONMENT
FROM rust:1.74-slim

# Upgrade System and Install dependencies
RUN apt-get update && \
  apt-get upgrade -y -o DPkg::Options::=--force-confold && \
  apt-get install -y -o DPkg::Options::=--force-confold curl unzip build-essential pkg-config libssl-dev mariadb-client libmariadb-dev default-libmysqlclient-dev

RUN curl -fsSL https://bun.sh/install | bash

RUN cargo install cargo-watch
RUN cargo install diesel_cli --no-default-features --features "mysql"
RUN mkdir -p /.cache/sccache && chmod a+rwx /.cache/sccache
RUN cargo install sccache --no-default-features
ENV RUSTC_WRAPPER sccache

ENV RUST_LOG_STYLE always
ENV RUST_BACKTRACE 1
ENV CARGO_HOME /tmp/.cargo
EXPOSE 8000
WORKDIR /usr/src/app

# Remember to mount source code to the container as volume!
CMD cargo watch --poll --why \
      -w resalt-config \
      -w resalt-frontend/src/lib.rs \
      -w resalt-frontend/src/build.rs \
      -w resalt-models \
      -w resalt-routes \
      -w resalt-salt \
      -w resalt-security \
      -w resalt-server \
      -w resalt-storage \
      -w resalt-storage-files \
      -w resalt-storage-mysql \
      -w resalt-storage-redis \
      -w resalt-update \
      -w Cargo.toml \
      -x run
