[package]
name = "resalt-security"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
argon2 = "0.5.0"
log = { workspace = true }
regex = "1.8.1"
resalt-models = { path = "../resalt-models" }
serde_json = "1.0.82"