[package]
name = "resalt-salt"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
actix-tls = { version = "3.0.3", features=["openssl"], default-features = false }
async-stream = "0.3.5"
awc = { version = "3.1.1", features=["openssl", "compress-gzip"], default-features = false }
futures = "0.3.21"
futures-core = "0.3.21"
http = "1.0.0"
log = { workspace = true }
openssl = "0.10.55"
resalt-config = { path = "../resalt-config" }
resalt-models = { path = "../resalt-models" }
resalt-storage = { path = "../resalt-storage" }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"