[package]
name = "resalt_security"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
argon2 = "0.5.0"
log = { workspace = true }
regex = "1.8.1"
resalt_models = { path = "../resalt_models" }
serde_json = "1.0.82"