[package]
name = "resalt_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
jsonpath_lib = "0.3.0"
log = { version = "0.4.17" }
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
serde_json = "1.0.82"
version-compare = "0.1.0"