[package]
name = "resalt_storage"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
resalt_security = { path = "../resalt_security" }
chrono = "0.4.24"
jsonpath_lib = "0.3.0"
serde_json = "1.0.82"
log = { workspace = true }
version-compare = "0.1.0"
rand = "0.8.5"