[package]
name = "resalt_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resalt_models = { path = "../resalt_models" }
chrono = "0.4"
