[package]
name = "resalt"
version = "0.3.1"
authors = ["Max Faxälv <max@foorack.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/resalt-dev/resalt"
license = "MIT"
description = "Resalt is a free, open-source, self-hosted, web-based administration and monitoring panel for SaltStack."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "workspace/resalt_config",
    "workspace/resalt_models",
    "workspace/resalt_salt",
    "workspace/resalt_security",
    "workspace/resalt_storage",
    "workspace/resalt_storage_mysql",
]

[dependencies]
# Own modules
resalt_config = { path = "workspace/resalt_config" }
resalt_ldap = { path = "workspace/resalt_ldap" }
resalt_models = { path = "workspace/resalt_models" }
resalt_pipeline = { path = "workspace/resalt_pipeline" }
resalt_salt = { path = "workspace/resalt_salt" }
resalt_security = { path = "workspace/resalt_security" }
resalt_storage = { path = "workspace/resalt_storage" }
resalt_storage_mysql = { path = "workspace/resalt_storage_mysql" }

# Web
actix-web = { version = "4.1.0", features=["compress-gzip"], default-features = false }
awc = { version = "3", features=["rustls", "compress-gzip"], default-features = false }

# Logging
log = { version = "0.4.17" }
env_logger = "0.10.0"

# Threading
tokio = { version = "1.20.0", features = ["rt-multi-thread"], default-features = false }
futures = "0.3.21"
clokwerk = "0.4.0"

# Utils
chrono = "0.4"
lazy_static = "1.4.0"
include_dir = "0.7.2"
regex = "1"

# Parsing
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
cargo_toml = "0.14.0"
urlencoding = "2.1.2"
jsonpath_lib = "0.3.0"

[package.metadata.resalt]
news = [
    "Resalt 0.3.1 released§Resalt 0.3.1 is now available. Fixed minor issue where Minion List would not paginate.",
    "Resalt 0.3.0 released§Resalt 0.3.0 is now available. Implemented the ability to store custom filters as \"Presets\". Additionally several minor UI and permission fixes.",
    "Resalt 0.2.2 released§Resalt 0.2.2 is now available. Reimplemented permission checking logic, ability to jump from Minion to Run directly, and several minor UI fixes.",
    "Resalt 0.2.1 released§Resalt 0.2.1 is now available. Minor fixes to Dashboard UI, and fixed a bug where the Salt API would reject Run requests even when a user is authenticated.",
    "Resalt 0.2.0 released§Resalt 0.2.0 is now available. This release includes a fix where compliance data wasn't stored when triggered from minion, improved permission checking, and several UI fixes.",
    "Resalt 0.1.6 released§Resalt 0.1.6 is now available. This release includes large UI updates, continued implementation of the permission system, the ability to see grains of offline minions, dependency updates, accessibility updates, enforcement of code linting, a severe improvement of compilation times for the frontend, and a lot of bug fixes.",
]
