[package]
name = "resalt"
version = "0.0.5"
edition = "2021"
readme = "README.md"
repository = "https://github.com/foorack/resalt"
license = "MIT"
description = "Resalt is a free, open-source, self-hosted, web-based administration and monitoring panel for SaltStack."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web
actix-web = { version = "4.1.0", features=["compress-gzip"], default-features = false }
awc = { version = "3", features=["rustls", "compress-gzip"], default-features = false }

# DB
diesel = { version = "2.0.0", features = ["mysql", "chrono", "r2d2"] }
diesel_migrations = "2.0.0"

# Auth
ldap3 = { version = "0.10.5", features = ["tls-native"], default-features = false }
argon2 = "0.4.1"

# Logging
log = { version = "0.4.16" }
env_logger = "0.9.0"

# Threading
async-stream = "0.3.3"
tokio = { version = "1.20.0", features = ["rt-multi-thread"], default-features = false }
futures = "0.3.21"
futures-core = "0.3.21"
clokwerk = "0.3.5"

# Utils
chrono = "0.4"
config = { version = "0.13.1", features = ["toml"],  default-features = false }
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.6.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
include_dir = "0.7.2"

# TLS
rustls = "0.20.6"
rustls-native-certs = "0.6.2"

# Parsing
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
cargo_toml = "0.11.5"
