[package]
name = "resalt"
version = "0.0.11"
authors = ["Max Faxälv <max@foorack.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/resalt-dev/resalt"
license = "MIT"
description = "Resalt is a free, open-source, self-hosted, web-based administration and monitoring panel for SaltStack."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "workspace/resalt_config",
    "workspace/resalt_models",
    "workspace/resalt_salt",
    "workspace/resalt_security",
    "workspace/resalt_storage",
    "workspace/resalt_storage_mysql",
]

[dependencies]
# Own Modules
resalt_config = { path = "workspace/resalt_config" }
resalt_models = { path = "workspace/resalt_models" }
resalt_pipeline = { path = "workspace/resalt_pipeline" }
resalt_salt = { path = "workspace/resalt_salt" }
resalt_security = { path = "workspace/resalt_security" }
resalt_storage = { path = "workspace/resalt_storage" }
resalt_storage_mysql = { path = "workspace/resalt_storage_mysql" }

# Web
actix-web = { version = "4.1.0", features=["compress-gzip"], default-features = false }
awc = { version = "3", features=["rustls", "compress-gzip"], default-features = false }

# Auth
ldap3 = { version = "0.10.5", features = ["tls-rustls"], default-features = false }

# Logging
log = { version = "0.4.17" }
env_logger = "0.9.0"

# Threading
async-stream = "0.3.3"
tokio = { version = "1.20.0", features = ["rt-multi-thread"], default-features = false }
futures = "0.3.21"
futures-core = "0.3.21"
clokwerk = "0.3.5"

# Utils
chrono = "0.4"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.6.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
include_dir = "0.7.2"

# TLS
rustls = "0.20.6"

# Parsing
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
cargo_toml = "0.11.5"
urlencoding = "2.1.2"
