version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: resalt
      MYSQL_PASSWORD: resalt
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  master:
    image: saltstack/salt:3004rc1
    hostname: master
    volumes:
      - ./docker/saltconfig/etc/master:/etc/salt/master:ro
      - ./docker/saltconfig/pillar:/srv/pillar:ro
      - ./docker/saltconfig/salt:/srv/salt:ro
    environment:
      - PYTHONUNBUFFERED=true
      - SALT_API_CONFIG={}
    ports:
      - "8080:8080"
  minion:
    image: saltstack/salt:3004rc1
    command: salt-minion -l info
    volumes:
      - ./docker/saltconfig/etc/minion:/etc/salt/minion:ro
    depends_on:
      - master
    deploy:
      replicas: 5

  frontend:
    user: "${UID:-1000}:${GID:-1000}"
    image: node:18-alpine
    volumes:
      - ./frontend:/usr/src/app
    command: /bin/sh -c "cd /usr/src/app && npm install && node ./node_modules/.bin/rollup -c -w"
    ports:
      - "5555:5555"
      - "35730:35730"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-devel
    volumes:
      - .:/usr/src/app:ro
      - /tmp/backend-target:/usr/src/app/target
    environment:
      - RUST_BACKTRACE=1
      - CARGO_HOME=/tmp/.cargo
      - RUST_LOG_STYLE=always # Add color to logs
      - RESALT_AUTH_LDAP_ENABLED=${RESALT_AUTH_LDAP_ENABLED:-}
      - RESALT_AUTH_LDAP_URL=${RESALT_AUTH_LDAP_URL:-}
      - RESALT_AUTH_LDAP_BASEDN=${RESALT_AUTH_LDAP_BASEDN:-}
      - RESALT_AUTH_LDAP_TLS_STARTTLS=${RESALT_AUTH_LDAP_TLS_STARTTLS:-}
      - RESALT_AUTH_LDAP_TLS_SKIPVERIFY=${RESALT_AUTH_LDAP_TLS_SKIPVERIFY:-}
      - RESALT_AUTH_LDAP_BIND_DN=${RESALT_AUTH_LDAP_BIND_DN:-}
      - RESALT_AUTH_LDAP_BIND_PASSWORD=${RESALT_AUTH_LDAP_BIND_PASSWORD:-}
      - RESALT_AUTH_LDAP_USER_FILTER=${RESALT_AUTH_LDAP_USER_FILTER:-}
      - RESALT_AUTH_LDAP_USER_ATTRIBUTE=${RESALT_AUTH_LDAP_USER_ATTRIBUTE:-}
      - RESALT_AUTH_SESSION_LIFESPAN=${RESALT_AUTH_SESSION_LIFESPAN:-}
      - RESALT_DATABASE_URL=${RESALT_DATABASE_URL:-}
      - RESALT_SALT_API_URL=${RESALT_SALT_API_URL:-http://master:8080}
      - RESALT_SALT_API_TOKEN=${RESALT_SALT_API_TOKEN:-}
      - RESALT_SALT_API_TLS_VERIFY=${RESALT_SALT_API_TLS_VERIFY:-}
      - RESALT_HTTP_FRONTEND_PROXY_ENABLED=${RESALT_HTTP_FRONTEND_PROXY_ENABLED:-true}
      - RESALT_HTTP_FRONTEND_THEME_COLOR=${RESALT_HTTP_FRONTEND_THEME_COLOR:-}
      - RESALT_HTTP_FRONTEND_PROXY_TARGET=${RESALT_HTTP_FRONTEND_PROXY_TARGET:-http://frontend:5555}
    ports:
      - "8000:8000"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
