version: '3'

services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --requirepass resalt
    ports:
      - "6379:6379"

  master:
    image: saltstack/salt:3006.4
    hostname: master
    volumes:
      - ./docs/docker/saltconfig/etc/master:/etc/salt/master:ro
      - ./docs/docker/saltconfig/pillar:/srv/pillar:ro
      - ./docs/docker/saltconfig/salt:/srv/salt:ro
    environment:
      - PYTHONUNBUFFERED=true
      - SALT_API_CONFIG={}
    ports:
      - "8080:8080"
  minion:
    image: saltstack/salt:3006.4
    command: salt-minion -l info
    volumes:
      - ./docs/docker/saltconfig/etc/minion:/etc/salt/minion:ro
    depends_on:
      - master
    deploy:
      replicas: 3

  # frontend:
  #   image: oven/bun:1.0.17
  #   volumes:
  #     - ./resalt-frontend/.svelte-kit/tsconfig.json:/home/bun/app/.svelte-kit/tsconfig.json
  #     - ./resalt-frontend/src:/home/bun/app/src
  #     - ./resalt-frontend/static:/home/bun/app/static
  #     - ./resalt-frontend/package.json:/home/bun/app/package.json
  #     - ./resalt-frontend/svelte.config.js:/home/bun/app/svelte.config.js
  #     - ./resalt-frontend/tsconfig.json:/home/bun/app/tsconfig.json
  #     - ./resalt-frontend/vite.config.ts:/home/bun/app/vite.config.ts
  #   command: /bin/sh -c "bun install && bun run dev"
  #   restart: always
  #   ports:
  #     - "5555:5555"
  frontend:
    image: oven/bun:1.0.17
    volumes:
      - ./resalt-frontend2/public:/home/bun/app/public
      - ./resalt-frontend2/src:/home/bun/app/src
      - ./resalt-frontend2/index.html:/home/bun/app/index.html
      - ./resalt-frontend2/package.json:/home/bun/app/package.json
      - ./resalt-frontend2/tsconfig.json:/home/bun/app/tsconfig.json
      - ./resalt-frontend2/tsconfig.node.json:/home/bun/app/tsconfig.node.json
      - ./resalt-frontend2/vite.config.ts:/home/bun/app/vite.config.ts
    command: /bin/sh -c "bun install && bun run dev"
    restart: always
    ports:
      - "5555:5555"
  backend:
    build:
      context: ./
      dockerfile: ./docs/docker/Dockerfile-devel
    volumes:
      - ./.cargo:/usr/src/app/.cargo:ro
      - ./Cargo.toml:/usr/src/app/Cargo.toml:ro
      - ./docs:/usr/src/app/docs
      - ./.gitignore:/usr/src/app/.gitignore:ro
      - ./resalt-api:/usr/src/app/resalt-api:ro
      - ./resalt-cli:/usr/src/app/resalt-cli:ro
      - ./resalt-config:/usr/src/app/resalt-config:ro
      - ./resalt-models:/usr/src/app/resalt-models:ro
      - ./resalt-routes:/usr/src/app/resalt-routes:ro
      - ./resalt-salt:/usr/src/app/resalt-salt:ro
      - ./resalt-security:/usr/src/app/resalt-security:ro
      - ./resalt-server:/usr/src/app/resalt-server:ro
      - ./resalt-storage:/usr/src/app/resalt-storage:ro
      - ./resalt-storage-files:/usr/src/app/resalt-storage-files:ro
      - ./resalt-storage-mysql:/usr/src/app/resalt-storage-mysql:ro
      - ./resalt-storage-redis:/usr/src/app/resalt-storage-redis:ro
      - ./resalt-update:/usr/src/app/resalt-update:ro
      # The following is because Bun does not support reading files which are mounted as read-only
      # Same as frontend, except /home/bun/app -> /usr/src/app/resalt-frontend
      - ./resalt-frontend/.svelte-kit/tsconfig.json:/usr/src/app/resalt-frontend/.svelte-kit/tsconfig.json
      - ./resalt-frontend/src:/usr/src/app/resalt-frontend/src
      - ./resalt-frontend/static:/usr/src/app/resalt-frontend/static
      - ./resalt-frontend/package.json:/usr/src/app/resalt-frontend/package.json
      - ./resalt-frontend/svelte.config.js:/usr/src/app/resalt-frontend/svelte.config.js
      - ./resalt-frontend/tsconfig.json:/usr/src/app/resalt-frontend/tsconfig.json
      - ./resalt-frontend/vite.config.ts:/usr/src/app/resalt-frontend/vite.config.ts
      # + extra
      - ./resalt-frontend/Cargo.toml:/usr/src/app/resalt-frontend/Cargo.toml:ro
    environment:
      RESALT_AUTH_FORWARD_ENABLED: ${RESALT_AUTH_FORWARD_ENABLED:-}
      RESALT_AUTH_SESSION_LIFESPAN: ${RESALT_AUTH_SESSION_LIFESPAN:-}
      RESALT_DATABASE_TYPE: ${RESALT_DATABASE_TYPE:-redis}
      RESALT_DATABASE_USERNAME: ${RESALT_DATABASE_USERNAME:-}
      RESALT_DATABASE_PASSWORD: ${RESALT_DATABASE_PASSWORD:-}
      RESALT_DATABASE_PASSWORDFILE: ${RESALT_DATABASE_PASSWORDFILE:-}
      RESALT_DATABASE_HOST: ${RESALT_DATABASE_HOST:-redis}
      RESALT_DATABASE_PORT: ${RESALT_DATABASE_PORT:-}
      RESALT_DATABASE_DATABASE: ${RESALT_DATABASE_DATABASE:-0}
      RESALT_METRICS_ENABLED: ${RESALT_METRICS_ENABLED:-}
      RESALT_SALT_API_URL: ${RESALT_SALT_API_URL:-http://master:8080}
      RESALT_SALT_API_TOKEN: ${RESALT_SALT_API_TOKEN:-}
      RESALT_SALT_API_TOKENFILE: ${RESALT_SALT_API_TOKENFILE:-}
      RESALT_SALT_API_TLS_SKIPVERIFY: ${RESALT_SALT_API_TLS_SKIPVERIFY:-}
      RESALT_HTTP_PORT: ${RESALT_HTTP_PORT:-}
      RESALT_HTTP_FRONTEND_PROXY_ENABLED: ${RESALT_HTTP_FRONTEND_PROXY_ENABLED:-true}
      RESALT_HTTP_FRONTEND_PROXY_TARGET: ${RESALT_HTTP_FRONTEND_PROXY_TARGET:-http://frontend:5555}
    restart: always
    ports:
      - "8000:8000"

  proxy:
    image: nginx:alpine-slim
    volumes:
      - ./docs/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "1234:80"
