version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: resalt
      MYSQL_PASSWORD: resalt
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  master:
    image: saltstack/salt:3005.1
    hostname: master
    volumes:
      - ./docker/saltconfig/etc/master:/etc/salt/master:ro
      - ./docker/saltconfig/pillar:/srv/pillar:ro
      - ./docker/saltconfig/salt:/srv/salt:ro
      - ./docker/saltconfig/rest_cherrypy_app.py:/usr/local/lib/python3.7/site-packages/salt/netapi/rest_cherrypy/app.py:ro
    environment:
      - PYTHONUNBUFFERED=true
      - SALT_API_CONFIG={}
    ports:
      - "8080:8080"
  minion:
    image: saltstack/salt:3005.1
    command: salt-minion -l info
    volumes:
      - ./docker/saltconfig/etc/minion:/etc/salt/minion:ro
    depends_on:
      - master
    deploy:
      replicas: 3

  frontend:
    user: "${UID:-1000}:${GID:-1000}"
    image: node:18-alpine
    volumes:
      - ./frontend:/usr/src/app
    command: /bin/sh -c "cd /usr/src/app && npm install && npm run dev"
    ports:
      - "5555:5555"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-devel
    volumes:
      - ./docker:/usr/src/app/docker:ro
      - ./docs:/usr/src/app/docs:ro
      - ./frontend:/usr/src/app/frontend:ro
      - ./src:/usr/src/app/src:ro
      - ./workspace:/usr/src/app/workspace:ro
      - ./.env:/usr/src/app/.env:ro
      - ./Cargo.toml:/usr/src/app/Cargo.toml:ro
      - ./README.md:/usr/src/app/README.md:ro
      - ./resalt.default.toml:/usr/src/app/resalt.default.toml:ro
      - /tmp/backend-target:/usr/src/app/target
    environment:
      RESALT_AUTH_FORWARD_ENABLED: ${RESALT_AUTH_FORWARD_ENABLED:-}
      RESALT_AUTH_LDAP_ENABLED: ${RESALT_AUTH_LDAP_ENABLED:-}
      RESALT_AUTH_LDAP_HOST: ${RESALT_AUTH_LDAP_HOST:-}
      RESALT_AUTH_LDAP_PORT: ${RESALT_AUTH_LDAP_PORT:-}
      RESALT_AUTH_LDAP_BASEDN: ${RESALT_AUTH_LDAP_BASEDN:-}
      RESALT_AUTH_LDAP_TLS_LDAPS: ${RESALT_AUTH_LDAP_TLS_LDAPS:-}
      RESALT_AUTH_LDAP_TLS_STARTTLS: ${RESALT_AUTH_LDAP_TLS_STARTTLS:-}
      RESALT_AUTH_LDAP_TLS_SKIPVERIFY: ${RESALT_AUTH_LDAP_TLS_SKIPVERIFY:-}
      RESALT_AUTH_LDAP_BIND_DN: ${RESALT_AUTH_LDAP_BIND_DN:-}
      RESALT_AUTH_LDAP_BIND_PASSWORD: ${RESALT_AUTH_LDAP_BIND_PASSWORD:-}
      RESALT_AUTH_LDAP_BIND_PASSWORDFILE: ${RESALT_AUTH_LDAP_BIND_PASSWORDFILE:-}
      RESALT_AUTH_LDAP_USER_FILTER: ${RESALT_AUTH_LDAP_USER_FILTER:-}
      RESALT_AUTH_LDAP_USER_ATTRIBUTE: ${RESALT_AUTH_LDAP_USER_ATTRIBUTE:-}
      RESALT_AUTH_SESSION_LIFESPAN: ${RESALT_AUTH_SESSION_LIFESPAN:-}
      RESALT_DATABASE_USERNAME: ${RESALT_DATABASE_USERNAME:-}
      RESALT_DATABASE_PASSWORD: ${RESALT_DATABASE_PASSWORD:-}
      RESALT_DATABASE_PASSWORDFILE: ${RESALT_DATABASE_PASSWORDFILE:-}
      RESALT_DATABASE_HOST: ${RESALT_DATABASE_HOST:-}
      RESALT_DATABASE_PORT: ${RESALT_DATABASE_PORT:-}
      RESALT_DATABASE_DATABASE: ${RESALT_DATABASE_DATABASE:-}
      RESALT_SALT_API_URL: ${RESALT_SALT_API_URL:-http://master:8080}
      RESALT_SALT_API_TOKEN: ${RESALT_SALT_API_TOKEN:-}
      RESALT_SALT_API_TOKENFILE: ${RESALT_SALT_API_TOKENFILE:-}
      RESALT_SALT_API_TLS_SKIPVERIFY: ${RESALT_SALT_API_TLS_SKIPVERIFY:-}
      RESALT_HTTP_PORT: ${RESALT_HTTP_PORT:-}
      RESALT_HTTP_FRONTEND_PROXY_ENABLED: ${RESALT_HTTP_FRONTEND_PROXY_ENABLED:-true}
      RESALT_HTTP_FRONTEND_PROXY_TARGET: ${RESALT_HTTP_FRONTEND_PROXY_TARGET:-http://frontend:5555}
      RESALT_HTTP_FRONTEND_THEME_ENABLED: ${RESALT_HTTP_FRONTEND_THEME_ENABLED:-}
      RESALT_HTTP_FRONTEND_THEME_COLOR: ${RESALT_HTTP_FRONTEND_THEME_COLOR:-}
      RESALT_HTTP_FRONTEND_THEME_DARK: ${RESALT_HTTP_FRONTEND_THEME_DARK:-}
    ports:
      - "8000:8000"

  proxy:
    image: nginx:alpine-slim
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "1234:80"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
