version: '3'

services:
  db:
    image: redis:7-alpine
    command: redis-server --save 60 1 --requirepass resalt
    ports:
      - "6379:6379"

  master:
    image: saltstack/salt:3006.3
    hostname: master
    volumes:
      - ./docker/saltconfig/etc/master:/etc/salt/master:ro
      - ./docker/saltconfig/pillar:/srv/pillar:ro
      - ./docker/saltconfig/salt:/srv/salt:ro
    environment:
      - PYTHONUNBUFFERED=true
      - SALT_API_CONFIG={}
    ports:
      - "8080:8080"
  minion:
    image: saltstack/salt:3006.3
    command: salt-minion -l info
    volumes:
      - ./docker/saltconfig/etc/minion:/etc/salt/minion:ro
    depends_on:
      - master
    deploy:
      replicas: 3

  frontend:
    image: oven/bun:1.0.7
    volumes:
      - ./frontend/.svelte-kit/tsconfig.json:/usr/src/app/.svelte-kit/tsconfig.json
      - ./frontend/src:/usr/src/app/src
      - ./frontend/static:/usr/src/app/static
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/svelte.config.js:/usr/src/app/svelte.config.js
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./frontend/vite.config.ts:/usr/src/app/vite.config.ts
    command: /bin/sh -c "cd /usr/src/app && bun install && bun run dev"
    restart: always
    ports:
      - "5555:5555"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-devel
    volumes:
      - ./docker:/usr/src/app/docker:ro
      - ./src:/usr/src/app/src:ro
      - ./workspace:/usr/src/app/workspace:ro
      - ./.env:/usr/src/app/.env:ro
      - ./Cargo.toml:/usr/src/app/Cargo.toml:ro
      - ./resalt.default.toml:/usr/src/app/resalt.default.toml:ro
    environment:
      RESALT_AUTH_FORWARD_ENABLED: ${RESALT_AUTH_FORWARD_ENABLED:-}
      RESALT_AUTH_LDAP_ENABLED: ${RESALT_AUTH_LDAP_ENABLED:-}
      RESALT_AUTH_LDAP_HOST: ${RESALT_AUTH_LDAP_HOST:-}
      RESALT_AUTH_LDAP_PORT: ${RESALT_AUTH_LDAP_PORT:-}
      RESALT_AUTH_LDAP_BASEDN: ${RESALT_AUTH_LDAP_BASEDN:-}
      RESALT_AUTH_LDAP_TLS_LDAPS: ${RESALT_AUTH_LDAP_TLS_LDAPS:-}
      RESALT_AUTH_LDAP_TLS_STARTTLS: ${RESALT_AUTH_LDAP_TLS_STARTTLS:-}
      RESALT_AUTH_LDAP_TLS_SKIPVERIFY: ${RESALT_AUTH_LDAP_TLS_SKIPVERIFY:-}
      RESALT_AUTH_LDAP_BIND_DN: ${RESALT_AUTH_LDAP_BIND_DN:-}
      RESALT_AUTH_LDAP_BIND_PASSWORD: ${RESALT_AUTH_LDAP_BIND_PASSWORD:-}
      RESALT_AUTH_LDAP_BIND_PASSWORDFILE: ${RESALT_AUTH_LDAP_BIND_PASSWORDFILE:-}
      RESALT_AUTH_LDAP_USER_FILTER: ${RESALT_AUTH_LDAP_USER_FILTER:-}
      RESALT_AUTH_LDAP_USER_ATTRIBUTE: ${RESALT_AUTH_LDAP_USER_ATTRIBUTE:-}
      RESALT_AUTH_SESSION_LIFESPAN: ${RESALT_AUTH_SESSION_LIFESPAN:-}
      RESALT_DATABASE_TYPE: ${RESALT_DATABASE_TYPE:-}
      RESALT_DATABASE_USERNAME: ${RESALT_DATABASE_USERNAME:-}
      RESALT_DATABASE_PASSWORD: ${RESALT_DATABASE_PASSWORD:-}
      RESALT_DATABASE_PASSWORDFILE: ${RESALT_DATABASE_PASSWORDFILE:-}
      RESALT_DATABASE_HOST: ${RESALT_DATABASE_HOST:-}
      RESALT_DATABASE_PORT: ${RESALT_DATABASE_PORT:-}
      RESALT_DATABASE_DATABASE: ${RESALT_DATABASE_DATABASE:-}
      RESALT_METRICS_ENABLED: ${RESALT_METRICS_ENABLED:-}
      RESALT_SALT_API_URL: ${RESALT_SALT_API_URL:-http://master:8080}
      RESALT_SALT_API_TOKEN: ${RESALT_SALT_API_TOKEN:-}
      RESALT_SALT_API_TOKENFILE: ${RESALT_SALT_API_TOKENFILE:-}
      RESALT_SALT_API_TLS_SKIPVERIFY: ${RESALT_SALT_API_TLS_SKIPVERIFY:-}
      RESALT_HTTP_PORT: ${RESALT_HTTP_PORT:-}
      RESALT_HTTP_FRONTEND_PROXY_ENABLED: ${RESALT_HTTP_FRONTEND_PROXY_ENABLED:-true}
      RESALT_HTTP_FRONTEND_PROXY_TARGET: ${RESALT_HTTP_FRONTEND_PROXY_TARGET:-http://frontend:5555}
      RESALT_HTTP_FRONTEND_THEME_ENABLED: ${RESALT_HTTP_FRONTEND_THEME_ENABLED:-}
      RESALT_HTTP_FRONTEND_THEME_COLOR: ${RESALT_HTTP_FRONTEND_THEME_COLOR:-}
      RESALT_HTTP_FRONTEND_THEME_DARK: ${RESALT_HTTP_FRONTEND_THEME_DARK:-}
    restart: always
    ports:
      - "8000:8000"

  proxy:
    image: nginx:alpine-slim
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "1234:80"

#  ldap-server:
#    image: osixia/openldap:1.3.0
#    restart: always
#    ports:
#      - "389:389"
#      - "636:636"
