[auth.ldap]
enabled = false
url = "ldap://ldap.example.com"
basedn = "dc=example,dc=com"

[auth.ldap.tls]
starttls = false
skipverify = true

[auth.ldap.bind]
dn = "cn=admin,dc=example,dc=com"
password = "secret"

[auth.ldap.user]
# OpenLDAP: (&(objectClass=inetOrgPerson)(uid=%s))
# Active Directory: (&(objectClass=user)(sAMAccountName=%s))
# AD with username or email: (&(objectClass=user)(|(sAMAccountName=%s)(mail=%s)))
filter = "(&(objectClass=inetOrgPerson)(uid=%s))"
# OpenLDAP: uid
# Active Directory: sAMAccountName
attribute = "uid"

[auth.session]
lifespan = 86400

[database]
url = "mysql://resalt:resalt@db/resalt"

[salt.api]
url = "https://master:8080"
# head /dev/urandom | tr -dc A-Za-z0-9 | head -c512; echo
#token = ""
[salt.api.tls]
verify = false

[http]
port = 8000
[http.frontend.theme]
color = "primary"
[http.frontend.proxy]
enabled = true
target = "http://frontend:5555"