#
# RESALT
#

[auth.forward]
# Only if you use active OAuth2 Proxy where authentication happens before requests reach Resalt
enabled = false

[auth.session]
lifespan = 43200

[database]
type = "redis"
username = "default"
password = "resalt"
passwordfile = ""
host = "db"
port = "6379"
database = "0"

[metrics]
enabled = false

[salt.api]
url = "https://master:8080"
# head /dev/urandom | tr -dc A-Za-z0-9 | head -c512; echo
#token = ""
tokenfile = ""
[salt.api.tls]
skipverify = true

[http]
port = 8000
[http.frontend.theme]
enabled = true
color = "primary"