[package]
name = "resalt_storage_files"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
resalt_security = { path = "../resalt_security" }
resalt_storage = { path = "../resalt_storage" }
chrono = "0.4.24"
log = { workspace = true }
rand = "0.8.5"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }