[package]
name = "resalt_scheduler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clokwerk = "0.4.0"
log = { workspace = true }
resalt_config = { path = "../resalt_config" }
resalt_ldap = { path = "../resalt_ldap" }
resalt_models = { path = "../resalt_models" }
resalt_storage = { path = "../resalt_storage" }
resalt_updater = { path = "../resalt_updater" }
tokio = { workspace = true }