[package]
name = "resalt-models"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axum = { workspace = true }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
chrono = { workspace = true }