[package]
name = "resalt_server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
actix-web = { workspace = true }
env_logger = "0.10.0"
log = { workspace = true }
resalt_config = { path = "../resalt_config" }
resalt_middleware = { path = "../resalt_middleware" }
resalt_routes = { path = "../resalt_routes" }
resalt_salt = { path = "../resalt_salt" }
resalt_scheduler = { path = "../resalt_scheduler" }
resalt_storage = { path = "../resalt_storage" }
resalt_storage_files = { path = "../resalt_storage_files" }
resalt_storage_mysql = { path = "../resalt_storage_mysql" }
resalt_storage_redis = { path = "../resalt_storage_redis" }
tokio = { workspace = true }
