[package]
name = "resalt-storage-files"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
log = { workspace = true }
resalt-models = { path = "../resalt-models" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }