FROM python:3.7-slim-buster

# Upgrade System and Install dependencies
RUN apt-get update && \
  apt-get upgrade -y -o DPkg::Options::=--force-confold && \
  apt-get install -y -o DPkg::Options::=--force-confold curl python3-mysqldb netcat

# Install Latest Salt from the stable Branch
RUN curl -L https://bootstrap.saltstack.com | sh -s -- -X -M -x python3 stable latest

# Install python dependencies
RUN apt-get install -y -o DPkg::Options::=--force-confold salt-api python3-openssl
RUN pip install honcho

# Copy needed files
COPY utils/Procfile .
