[package]
name = "resalt-models"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = { workspace = true }
jsonpath_lib = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
version-compare = "0.1.1"