[package]
name = "resalt-storage-redis"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
r2d2 = "0.8.10"
redis = { version = "0.24.0", features = ["r2d2", "keep-alive", "json"], default-features = false }
resalt-models = { path = "../resalt-models" }
