[package]
name = "resalt_storage_redis"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
resalt_security = { path = "../resalt_security" }
resalt_storage = { path = "../resalt_storage" }
chrono = "0.4.24"
redis = "0.23.1"
r2d2_redis = "0.14.0"
log = { version = "0.4.17" }
rand = "0.8.5"
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }