[package]
name = "resalt_storage_redis"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
resalt_security = { path = "../resalt_security" }
resalt_storage = { path = "../resalt_storage" }
chrono = "0.4.24"
redis = { version = "0.23.1", features = ['r2d2'] }
r2d2 = "0.8.10"
log = { workspace = true }
rand = "0.8.5"
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }