[package]
name = "resalt_updater"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
awc = { version = "3.1.1", features=["openssl", "compress-gzip"], default-features = false }
toml = { version = "0.8.8", features = ["parse"], default-features = false }
chrono = "0.4.24"
log = { workspace = true }
lazy_static = "1.4.0"