[package]
name = "resalt_mysql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
diesel = { version = "2.0.0", features = ["mysql", "chrono", "r2d2"] }
diesel_migrations = "2.0.0"
log = { version = "0.4.17" }
rand = "0.8.5"
resalt_models = { path = "../resalt_models" }
resalt_security = { path = "../resalt_security" }
resalt_storage = { path = "../resalt_storage" }
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }