[package]
name = "resalt_mysql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.17" }
diesel = { version = "2.0.0", features = ["mysql", "chrono", "r2d2"] }
diesel_migrations = "2.0.0"
chrono = "0.4"
resalt_storage = { path = "../resalt_storage" }
