[package]
name = "resalt_storage_mysql"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = "0.4.24"
diesel = { version = "2.1.0", features = ["mysql", "chrono", "r2d2"] }
diesel_migrations = "2.1.0"
log = { workspace = true }
resalt_config = { path = "../resalt_config" }
resalt_models = { path = "../resalt_models" }
resalt_storage = { path = "../resalt_storage" }
serde_json = "1.0.82"
uuid = { version = "1.1.2", features = ["serde", "v4"] }