[package]
name = "resalt_config"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
config = { version = "0.13.1", features = ["toml"],  default-features = false }
lazy_static = "1.4.0"
log = { workspace = true }
rand = "0.8.5"