[package]
name = "resalt-security"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
argon2 = { version = "0.5.2", features = ["alloc", "password-hash"], default-features = false }