on: [push]

name: CI

env: 
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    name: Frontend Lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-v18-${{ hashFiles('./frontend/package-lock.json') }}
      
      - name: "cd into /frontend and lint"
        run: |
          cd frontend
          npm install
          npm run lint

  backend-lint:
    runs-on: ubuntu-latest
    name: Backend Lint
    # Setup Rust and run "cargo clippy"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: mkdir ./frontend/build to fake frontend being built while linting
        run: mkdir -p ./frontend/build
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets --

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-v18-${{ hashFiles('./frontend/package-lock.json') }}

      - name: Read version number
        run: |
          echo "spec_version=$(grep "version = " Cargo.toml | head -n 1  | cut -d '"' -f 2)" >> $GITHUB_ENV
      - name: Print version number
        run: echo ${{ env.spec_version }}
      - name: Build Docker image
        run: docker build . -t ghcr.io/resalt-dev/resalt:${{ env.spec_version }}

      # Below only happens if tag is created

      - name: Log in to Github Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
      - name: Push Docker image
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: docker push ghcr.io/resalt-dev/resalt:${{ env.spec_version }}
